pipeline {
    agent { label 'docker' }

    environment {
        FE_BE = 'fe'

        DOCKERHUB_CREDENTIALS = credentials('docker-creds') // configure jenkins with your credentials 
        DOCKER_REGISTRY = 'frenzy669' //'YOUR DOCKERHUB USERID'
        REPO_NAME = "$FE_BE-exam"  //### IMAGE NAME -  Change to 'be-exam' WHEN creating the backend pipeline
        IMAGE_TAG = "${env.BUILD_NUMBER}"

        HOME_DIR = '/home/ubuntu/workarea/jb/'
        
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'workshop/argo-jenkins-exam', url: 'https://github.com/AviBernstock/devopshift-welcome.git'
            }
        }

        stage('Lint & Security Scan') {
            parallel {
                //dir("$HOME_DIR"){
                    stage('Flake8 Linting') {
                        steps {
                            //dir("${env.HOME_DIR}"){
                            script {
                                sh """echo 'in stage Flake8 Linting'"""
                                //     if ! command -v flake8 &> /dev/null; then
                                //         echo 'Installing flake8...'
                                //         pip install flake8
                                //     fi
                                //     pwd
                                //     ls
                                //     # flake8 ./exam-code/docker/${env.FE_BE}/src/main${env.FE_BE}.py
                                // """  // // Change to `/home/ubuntu/workarea/jb/exam-code/docker/be/src/mainbe.py` for backend pipeline
                            }
                            //}
                        }
                    }

                    stage('Bandit Security Scan') {
                        steps {
                            //dir("${env.HOME_DIR}"){
                            script {
                                sh """echo 'in stage Bandit Security Scan'"""
                                    
                                //     if ! command -v bandit &> /dev/null; then
                                //         echo 'Installing flake8...'
                                //         pip install bandit
                                //     fi

                                //     pwd
                                //     ls
                                //     bandit -r ./exam-code/docker/${env.FE_BE}/src/main${env.FE_BE}.py
                                // """  //'bandit -r ./src/mainfe.py'  // Change to `/home/ubuntu/workarea/jb/exam-code/docker/be/src/mainbe.py` for backend pipeline
                            }
                            //}
                        }
                    }
                //}
            }
        }
        
        stage('Install Dependencies') {
            steps {
                script {
                    sh "pip install -r ./exam-code/docker/${env.FE_BE}/requirements.txt" 
                }
            }
        }
        
        stage('Build Docker Image') { //todo: update the <.....>
            steps {
                script {   // Locate the Dockerfile under the fe/be projects
                    sh "docker build -t ${env.DOCKER_REGISTRY}/your-app:${env.BUILD_NUMBER} ."
                    sh "docker tag ${DOCKER_REGISTRY}/your-app:${BUILD_NUMBER} ${DOCKER_REGISTRY}/your-app:latest"
                }
            }
        }

        stage('Run Tests in Container') {
            steps {
                script {
                    sh "docker run --rm ${DOCKER_REGISTRY}/your-app:${BUILD_NUMBER} pytest tests/"  
                }
            }
        }

        stage('Integration Test with Docker Compose') { //maybe change from "docker-compose" to "docker compose"
            steps {
                script {
                    sh """docker-compose up -d
                        sleep 10  # Allow services to start
                        curl -f http://localhost:5002 || exit 1  # Adjust for backend if needed
                        docker-compose down
                    """
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    sh """echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin
                        docker push ${DOCKER_REGISTRY}/your-app:${BUILD_NUMBER}
                        docker push ${DOCKER_REGISTRY}/your-app:latest
                    """
                }
            }
        
        }
    }
}
